AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  spotify-noti

  Sample SAM Template for spotify-noti

Globals:
  Function:
    Timeout: 200
    MemorySize: 128
    Runtime: python3.9
    Architectures:
      - arm64

Resources:
  SpotifyCheckFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: spotify-check/
      Handler: app.lambda_handler
      Policies: 
        - SecretsManagerReadWrite

      Events:
        SpotifyCheck:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /check
            Method: get
  SendEmailFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: send-email/
      Handler: app.lambda_handler
      Events:
        SendEmail:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /email
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SpotifyCheckApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/check/"
  SpotifyCheckFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SpotifyCheckFunction.Arn
  SpotifyCheckFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SpotifyCheckFunctionRole.Arn
  SendEmailApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/email/"
  SendEmailFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SendEmailFunction.Arn
  SendEmailFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SendEmailFunctionRole.Arn
